### ISSUE TITLE
Dynamic roughness and Bowing values

### ISSUE THREAD

**Issue by pshihn** [pshihn/rough#114]
When drawing long lines (or polygons), the roughness looks more pronounced than in smaller sized shapes. 
Options are:
* Automatically reduce the roughness and bowing as an inverse relation to length of the line
* Breakup the line into `n` number of lines to maintain the similar roughness feel
* If doing automatic, is it a linear relationship or an exponential one?

**Comment by cpryland** [comment]
These are all good questions.

Seems like ellipsi were the most pronounced.

You'd have to handle roughness/bowing as an inverse relation of the general size, perhaps using the longest side of any figure's bounding box as the "general size". That's what we tried but it got hairy quickly and we never finished the experimentation.

**Comment by pshihn** [comment]
Thats really good to know. I really want this to work for all user cases, as the interest in this keep growing. 
For an ellipse, the relationship will definitely be non-linear. 
Perhaps, it would be good for me to experiment with different shapes and sized and tabulate the output.

**Comment by cpryland** [comment]
Boy, yes, if you could get anywhere near a good solution across a range of sizes (including down to 4-6 pixels/pts and up to 2K pixels/pts), that would be a huge boon for the whole rough.js ecosystem.

My other problem with rough.js, which isn't really yours, is that I have to generate the roughened ellipse/polygon separately from its fill (since I can't use the SVG fallback for clipping in my XD plugin), which means the fill is often highly mis-aligned with the border.

**Comment by pshihn** [comment]
This was added in 4.0 https://github.com/pshihn/rough/pull/121
It also supports seeding
