### ISSUE TITLE
Parse an existing SVG?

### ISSUE THREAD

**Issue by abritinthebay** [pshihn/rough#18]
As it already has Path support I imagine this would be more about actually finding the paths in an svg and passing them in one by one (including fill color).

Thoughts on practicality? Seems like it would be a useful feature. I know it would involve some kind of really gnarly regex...

**Comment by abritinthebay** [comment]
Slight snarly regex's to get...

fills: `/<path (?:.+)fill="([^"]+)"(?:.+)\/>/gi`
path data = `/<path (?:.+)d="([^"]+)"(?:.+)\/>/gi`

**Comment by abritinthebay** [comment]
I guess the question is: PRs welcome?

**Comment by pshihn** [comment]
PRs always welcome. I am planning out the next release with more advanced native SVG support -> i.e. create sketchy SVG nodes rather than draw on canvas. 
But, what you're proposing is also good for the current Canvas version. I'd hate to duplicate code and would like keep the API future compatible.
So, if you have a PR, I can include it in the next release.

**Comment by pshihn** [comment]
Btw, SVGs are just DOM. You may be able to use DOM parsing rather than regex to parse not just paths but other SVG primitives as well.

**Comment by abritinthebay** [comment]
True, I was thinking Node... but it wouldn't have a canvas at that point anyhow either. So I may as well just use DOMParser.

**Comment by pshihn** [comment]
Rough.js now supports SVG rendering https://github.com/pshihn/rough/pull/49
Thought that is not part of this issue directly, I think parsing for files can be build on top as @sbrugman suggested.
