### ISSUE TITLE
Event Handling

### ISSUE THREAD

**Issue by julianfrank** [pshihn/rough#21]
How do I handle click/touch/drag events? 
And make my object react according to these events?

**Comment by BrianDGLS** [comment]
Click, touch, and drag events can be used as specified in [Foundation HTML5 Animation](https://lamberta.github.io/html5-animation/), see chapter 7.

Handling user interaction is not in the scope of this library.

Referencing the library description from the README, it is used only to `draw`.

```
Rough.js is a light weight (~8k), Canvas based library that lets you draw in a sketchy, 
hand-drawn-like, style. The library defines primitives to draw lines, curves, arcs, 
polygons, circles, and ellipses. It also supports drawing SVG paths.
```

**Comment by pshihn** [comment]
There may be other frameworks as @BrianDGLS suggested that you can use with canvas for that. The goal here is to provide drawing primitives that could work with anything else you may want to use. 

Note that I am planning a pure SVG renderer for RoughJS as well which will generate SVG nodes rather than draw on canvas. With those, you can use standard DOM event handling.

**Comment by julianfrank** [comment]
Any examples there to use native dom events.... Would be nice in main readme?
